from .papers import Paper
from .papers import Paper
from .questions import Question
from .subject import Subject
from .discipline import Discipline
from .paper_type import Papers_type
from .answers import Answer
from .tags import Tags
from .topic import Topic
from .image import Image