# Generated by Django 3.2.7 on 2021-09-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='uploads/papers'),
        ),
    ]
