# Generated by Django 3.2.7 on 2021-09-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_paper_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='date',
            field=models.DateField(),
        ),
    ]
